# Generated by Django 4.2.5 on 2023-09-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discription',
            new_name='description',
        ),
    ]
